### ISSUE TITLE
Weather not updating

### ISSUE THREAD

**Issue by anthonyjclarke** [hwiguna/HariFun_166_Morphing_Clock#5]
I'm finding that intermittently the weather is not updating, I'm not plugged into a serial monitor so can't see any logs... clock timing is spot on... but a couple of times I see the weather is way out....

A simple reset, reconnect and it gets corrected.

Any suggestions, please?

https://photos.app.goo.gl/rWLJWug3ZGwjwXe37

**Comment by hwiguna** [comment]
@anthonyjclarke , unfortunately, I know nothing about the weather code.  Someone else wrote that feature.  Try looking in the comment in the code, it probably shows the github page with that weather code.
